// Intelligent Assistant/frontend/src/components/agents/CreateAgentModal.jsx
import React, { useState } from 'react'

/**
 * 新建智能体 — 模态框
 *
 * Props:
 *   open    : boolean
 *   onClose : () => void
 *   onSubmit: (draft) => void
 */
function CreateAgentModal({ open, onClose, onSubmit }) {
  /* ========== 表单状态 ========== */
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const [category, setCategory] = useState('custom')
  const [icon, setIcon] = useState('smart_toy')
  const [triggerCommand, setTriggerCommand] = useState('')
  const [systemPrompt, setSystemPrompt] = useState('')
  const [welcomeMessage, setWelcomeMessage] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [errors, setErrors] = useState({})

  /* ========== 选项常量 ========== */
  const CATEGORY_OPTIONS = [
    { key: 'custom',     label: '通用自定义', icon: 'smart_toy' },
    { key: 'office',     label: '办公效率',   icon: 'work' },
    { key: 'dev',        label: '研发辅助',   icon: 'code' },
    { key: 'test',       label: '测试工具',   icon: 'bug_report' },
    { key: 'ops',        label: '运维工具',   icon: 'settings' },
    { key: 'operation',  label: '运营工具',   icon: 'campaign' },
  ]

  const ICON_OPTIONS = [
    'smart_toy', 'auto_awesome', 'edit', 'description', 'slideshow',
    'table_chart', 'palette', 'language', 'code', 'analytics',
    'podcasts', 'forum', 'campaign', 'insights', 'auto_stories',
    'support_agent', 'psychology', 'travel_explore', 'science',
    'monitor_heart', 'rocket_launch', 'shield', 'workspace_premium',
  ]

  const BG_OPTIONS = [
    'linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)',
    'linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)',
    'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
    'linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)',
    'linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)',
    'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)',
    'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  ]

  if (!open) return null

  /* ========== 行为 ========== */
  const handleClose = () => {
    if (submitting) return
    reset()
    onClose()
  }

  const reset = () => {
    setName('')
    setDescription('')
    setCategory('custom')
    setIcon('smart_toy')
    setTriggerCommand('')
    setSystemPrompt('')
    setWelcomeMessage('')
    setErrors({})
  }

  const validate = () => {
    const e = {}
    if (!name.trim()) e.name = '请输入智能体名称'
    if (name.trim().length > 30) e.name = '名称不能超过 30 字'
    if (!description.trim()) e.description = '请输入智能体简介'
    if (description.trim().length > 120) e.description = '简介不能超过 120 字'
    if (systemPrompt && systemPrompt.length > 2000) e.systemPrompt = '人设不能超过 2000 字'
    setErrors(e)
    return Object.keys(e).length === 0
  }

  const handleSubmit = async (ev) => {
    ev.preventDefault()
    if (!validate()) return
    setSubmitting(true)
    try {
      // 模拟异步保存 (后续可对接后端)
      await new Promise((r) => setTimeout(r, 200))
      const idx = ICON_OPTIONS.indexOf(icon)
      const iconBg = BG_OPTIONS[Math.max(0, idx) % BG_OPTIONS.length]
      onSubmit?.({
        name,
        description,
        category,
        icon,
        iconBg,
        systemPrompt,
        triggerCommand,
        welcomeMessage,
        colorTheme: 'primary',
      })
      reset()
    } finally {
      setSubmitting(false)
    }
  }

  /* ========== 渲染 ========== */
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4 tab-fade-in"
      style={{ backgroundColor: 'color-mix(in srgb, var(--color-on-surface) 60%, transparent)' }}
      onClick={handleClose}
    >
      <form
        onSubmit={handleSubmit}
        onClick={(e) => e.stopPropagation()}
        className="w-full max-w-2xl rounded-2xl shadow-2xl flex flex-col max-h-[90vh]"
        style={{
          backgroundColor: 'var(--color-surface-container-lowest)',
          border: '1px solid var(--color-outline-variant)',
        }}
      >
        {/* Header */}
        <div
          className="flex items-center justify-between px-6 py-4 border-b transition-colors duration-200"
          style={{ borderColor: 'var(--color-outline-variant)' }}
        >
          <div className="flex items-center gap-2">
            <span
              className="material-symbols-outlined text-[22px]"
              style={{ color: 'var(--color-primary)' }}
            >
              add_circle
            </span>
            <h2
              className="text-lg font-semibold transition-colors duration-200"
              style={{ color: 'var(--color-on-surface)' }}
            >
              新建智能体
            </h2>
            <span
              className="text-[10px] px-1.5 py-0.5 rounded font-semibold"
              style={{
                backgroundColor: 'color-mix(in srgb, var(--color-primary) 12%, transparent)',
                color: 'var(--color-primary)',
              }}
            >
              自定义
            </span>
          </div>
          <button
            type="button"
            onClick={handleClose}
            className="w-8 h-8 rounded-md flex items-center justify-center transition-all duration-200 cursor-pointer"
            style={{ color: 'var(--color-on-surface-variant)' }}
            onMouseEnter={(e) => {
              e.currentTarget.style.backgroundColor = 'var(--color-surface-container-high)'
              e.currentTarget.style.color = 'var(--color-on-surface)'
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.backgroundColor = 'transparent'
              e.currentTarget.style.color = 'var(--color-on-surface-variant)'
            }}
            aria-label="关闭"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-6 py-5 flex flex-col gap-5">
          {/* 预览卡片 */}
          <AgentPreview
            name={name}
            description={description}
            icon={icon}
            category={category}
          />

          {/* 名称 + 分类 */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <Field
              label="智能体名称"
              required
              error={errors.name}
              htmlFor="agent-name"
              counter={`${name.length}/30`}
            >
              <input
                id="agent-name"
                type="text"
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="例如：周报生成助手"
                maxLength={30}
                className="w-full rounded-lg px-3 py-2.5 outline-none focus:ring-2 transition-all duration-200 text-sm"
                style={inputStyle(errors.name)}
              />
            </Field>

            <Field label="所属分类" htmlFor="agent-category">
              <select
                id="agent-category"
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className="w-full rounded-lg px-3 py-2.5 outline-none focus:ring-2 transition-all duration-200 text-sm appearance-none cursor-pointer"
                style={{
                  ...inputStyle(),
                  backgroundImage:
                    'url("data:image/svg+xml;utf8,<svg xmlns=\'http://www.w3.org/2000/svg\' viewBox=\'0 0 24 24\' fill=\'%23999\'><path d=\'M7 10l5 5 5-5z\'/></svg>")',
                  backgroundRepeat: 'no-repeat',
                  backgroundPosition: 'right 8px center',
                  backgroundSize: '20px',
                  paddingRight: '32px',
                }}
              >
                {CATEGORY_OPTIONS.map((c) => (
                  <option key={c.key} value={c.key}>
                    {c.label}
                  </option>
                ))}
              </select>
            </Field>
          </div>

          {/* 简介 */}
          <Field
            label="功能简介"
            required
            error={errors.description}
            htmlFor="agent-desc"
            counter={`${description.length}/120`}
          >
            <textarea
              id="agent-desc"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="一句话说明这个智能体能解决什么问题"
              maxLength={120}
              rows={2}
              className="w-full rounded-lg px-3 py-2.5 outline-none focus:ring-2 transition-all duration-200 text-sm resize-none"
              style={inputStyle(errors.description)}
            />
          </Field>

          {/* 图标选择 */}
          <Field label="选择图标" htmlFor="agent-icon">
            <div className="flex items-center gap-2 flex-wrap">
              {ICON_OPTIONS.map((ic) => {
                const active = ic === icon
                return (
                  <button
                    key={ic}
                    type="button"
                    onClick={() => setIcon(ic)}
                    className="w-9 h-9 rounded-lg flex items-center justify-center transition-all duration-200 cursor-pointer"
                    style={
                      active
                        ? {
                            backgroundColor: 'var(--color-primary)',
                            color: 'var(--color-on-primary)',
                          }
                        : {
                            backgroundColor: 'var(--color-surface-container)',
                            color: 'var(--color-on-surface-variant)',
                            border: '1px solid var(--color-outline-variant)',
                          }
                    }
                    title={ic}
                  >
                    <span className="material-symbols-outlined text-[18px]">{ic}</span>
                  </button>
                )
              })}
            </div>
          </Field>

          {/* 触发命令 */}
          <Field
            label="触发命令（可选）"
            htmlFor="agent-cmd"
            hint="在聊天输入框中以 /xxx 形式快速调用"
          >
            <div className="flex items-center">
              <span
                className="px-3 py-2.5 rounded-l-lg text-sm font-mono"
                style={{
                  backgroundColor: 'var(--color-surface-container-high)',
                  color: 'var(--color-on-surface-variant)',
                  border: '1px solid var(--color-outline-variant)',
                  borderRight: 'none',
                }}
              >
                /
              </span>
              <input
                id="agent-cmd"
                type="text"
                value={triggerCommand}
                onChange={(e) => setTriggerCommand(e.target.value.replace(/[\s/]/g, ''))}
                placeholder="mybot"
                maxLength={20}
                className="flex-1 rounded-r-lg px-3 py-2.5 outline-none focus:ring-2 transition-all duration-200 text-sm font-mono"
                style={{
                  backgroundColor: 'var(--color-surface-container)',
                  color: 'var(--color-on-surface)',
                  border: '1px solid var(--color-outline-variant)',
                }}
              />
            </div>
          </Field>

          {/* 人设 / 系统提示词 */}
          <Field
            label="人设 / 系统提示词（可选）"
            htmlFor="agent-prompt"
            hint="定义智能体的角色定位、回答风格、注意事项等"
            error={errors.systemPrompt}
            counter={`${systemPrompt.length}/2000`}
          >
            <textarea
              id="agent-prompt"
              value={systemPrompt}
              onChange={(e) => setSystemPrompt(e.target.value)}
              placeholder={`你是一位专业的 [角色]，擅长 [领域]…\n回答要求：\n1. ...\n2. ...`}
              rows={5}
              className="w-full rounded-lg px-3 py-2.5 outline-none focus:ring-2 transition-all duration-200 text-xs font-mono resize-none"
              style={inputStyle(errors.systemPrompt)}
            />
          </Field>

          {/* 欢迎语 */}
          <Field
            label="欢迎语（可选）"
            htmlFor="agent-welcome"
            hint="用户首次与该智能体对话时展示的开场白"
          >
            <textarea
              id="agent-welcome"
              value={welcomeMessage}
              onChange={(e) => setWelcomeMessage(e.target.value)}
              placeholder="你好！我是你的 [角色]，可以帮你 …"
              rows={2}
              maxLength={200}
              className="w-full rounded-lg px-3 py-2.5 outline-none focus:ring-2 transition-all duration-200 text-sm resize-none"
              style={inputStyle()}
            />
          </Field>
        </div>

        {/* Footer */}
        <div
          className="flex items-center justify-end gap-3 px-6 py-4 border-t transition-colors duration-200"
          style={{ borderColor: 'var(--color-outline-variant)' }}
        >
          <button
            type="button"
            onClick={handleClose}
            className="px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 cursor-pointer"
            style={{
              backgroundColor: 'transparent',
              color: 'var(--color-on-surface-variant)',
              border: '1px solid var(--color-outline-variant)',
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.backgroundColor = 'var(--color-surface-container)'
              e.currentTarget.style.color = 'var(--color-on-surface)'
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.backgroundColor = 'transparent'
              e.currentTarget.style.color = 'var(--color-on-surface-variant)'
            }}
          >
            取消
          </button>
          <button
            type="submit"
            disabled={submitting}
            className="px-4 py-2 rounded-lg text-sm font-medium transition-all duration-200 cursor-pointer disabled:opacity-60 disabled:cursor-not-allowed inline-flex items-center gap-1.5"
            style={{
              backgroundColor: 'var(--color-primary)',
              color: 'var(--color-on-primary)',
            }}
            onMouseEnter={(e) => {
              if (!submitting) e.currentTarget.style.opacity = '0.9'
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.opacity = '1'
            }}
          >
            {submitting && (
              <span className="material-symbols-outlined text-[16px] animate-spin">
                progress_activity
              </span>
            )}
            {submitting ? '创建中…' : '创建智能体'}
          </button>
        </div>
      </form>
    </div>
  )
}

/* ===== 实时预览卡片 ===== */
function AgentPreview({ name, description, icon, category }) {
  const idx = ['smart_toy', 'auto_awesome', 'edit', 'description', 'slideshow',
    'table_chart', 'palette', 'language', 'code', 'analytics',
    'podcasts', 'forum', 'campaign', 'insights', 'auto_stories',
    'support_agent', 'psychology', 'travel_explore', 'science',
    'monitor_heart', 'rocket_launch', 'shield', 'workspace_premium',
  ].indexOf(icon)
  const BG_OPTIONS = [
    'linear-gradient(135deg, #a1c4fd 0%, #c2e9fb 100%)',
    'linear-gradient(135deg, #ff9a9e 0%, #fad0c4 100%)',
    'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
    'linear-gradient(135deg, #84fab0 0%, #8fd3f4 100%)',
    'linear-gradient(135deg, #fccb90 0%, #d57eeb 100%)',
    'linear-gradient(135deg, #e0c3fc 0%, #8ec5fc 100%)',
    'linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)',
    'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
  ]
  const iconBg = BG_OPTIONS[Math.max(0, idx) % BG_OPTIONS.length]
  const CATEGORY_LABELS = {
    custom: '通用自定义', office: '办公效率', dev: '研发辅助',
    test: '测试工具', ops: '运维工具', operation: '运营工具',
  }

  return (
    <div
      className="rounded-xl p-3 flex items-center gap-3"
      style={{
        backgroundColor: 'var(--color-surface-container)',
        border: '1px dashed var(--color-outline-variant)',
      }}
    >
      <span
        className="text-[10px] font-semibold uppercase tracking-wider"
        style={{ color: 'var(--color-on-surface-variant)' }}
      >
        预览
      </span>
      <div
        className="w-10 h-10 rounded-xl flex items-center justify-center shrink-0"
        style={{ background: iconBg }}
      >
        <span className="material-symbols-outlined text-[22px] text-white">
          {icon}
        </span>
      </div>
      <div className="flex-1 min-w-0">
        <p
          className="text-sm font-semibold truncate"
          style={{ color: 'var(--color-on-surface)' }}
        >
          {name || '未命名智能体'}
        </p>
        <p
          className="text-[11px] truncate"
          style={{ color: 'var(--color-on-surface-variant)' }}
        >
          {description || '一句话说明这个智能体能解决什么问题'}
        </p>
      </div>
      <span
        className="text-[10px] px-1.5 py-0.5 rounded font-semibold shrink-0"
        style={{
          backgroundColor: 'color-mix(in srgb, var(--color-primary) 12%, transparent)',
          color: 'var(--color-primary)',
        }}
      >
        {CATEGORY_LABELS[category] || '通用自定义'}
      </span>
    </div>
  )
}

/* ===== Field 通用容器 ===== */
function Field({ label, required, error, htmlFor, children, counter, hint }) {
  return (
    <div className="flex flex-col gap-1.5">
      <div className="flex items-center justify-between">
        <label
          htmlFor={htmlFor}
          className="text-xs font-medium transition-colors duration-200"
          style={{ color: 'var(--color-on-surface-variant)' }}
        >
          {label} {required && <span style={{ color: 'var(--color-error)' }}>*</span>}
        </label>
        {counter && (
          <span
            className="text-[10px]"
            style={{ color: 'var(--color-on-surface-variant)' }}
          >
            {counter}
          </span>
        )}
      </div>
      {children}
      {hint && !error && (
        <span
          className="text-[11px] transition-colors duration-200"
          style={{ color: 'var(--color-on-surface-variant)', opacity: 0.75 }}
        >
          {hint}
        </span>
      )}
      {error && (
        <span
          className="text-[11px] transition-colors duration-200"
          style={{ color: 'var(--color-error)' }}
        >
          {error}
        </span>
      )}
    </div>
  )
}

/* ===== input 通用样式 ===== */
function inputStyle(hasError) {
  return {
    backgroundColor: 'var(--color-surface-container)',
    color: 'var(--color-on-surface)',
    border: `1px solid ${hasError ? 'var(--color-error)' : 'var(--color-outline-variant)'}`,
  }
}

export default CreateAgentModal

// frontend/src/components/CreateAgentModal.vue
<template>
  <!-- Teleport 到 body,逃出任何祖先的 transform/filter/perspective/will-change 包含块 -->
  <!-- 防止 position:fixed 失效,确保弹窗始终相对于视口居中 -->
  <Teleport to="body">
    <Transition name="ca-fade">
      <div v-if="open" class="ca-mask" @mousedown.self="onClose">
        <div class="ca-modal" role="dialog" aria-modal="true">
          <!-- ============== HEADER (对齐 cs-modal__head) ============== -->
          <header class="ca-modal__head">
            <div class="ca-modal__title">
              <span class="ca-modal__icon" :style="{ background: form.color_theme + '22', color: form.color_theme }">
                <el-icon :size="18"><component :is="iconComp(form.icon)" /></el-icon>
              </span>
              <div>
                <h3>新建智能体</h3>
                <p>自定义 AI 助手 · 绑定人设与触发命令,创建后出现在「我的自定义智能体」分块</p>
              </div>
            </div>
            <button class="ca-modal__close" @click="onClose" aria-label="关闭">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">
                <path d="M18 6 6 18M6 6l12 12"/>
              </svg>
            </button>
          </header>

          <form class="ca-modal__body" @submit.prevent="handleSubmit">
            <!-- 智能体名称 (对齐 cs-field) -->
            <div class="ca-field">
              <label>智能体名称 <span class="req">*</span></label>
              <input
                v-model.trim="form.name"
                type="text"
                placeholder="例如:周报生成助手"
                maxlength="30"
              />
              <span v-if="errors.name" class="ca-field__err">{{ errors.name }}</span>
              <span v-else class="ca-field__hint">{{ form.name.length }} / 30</span>
            </div>

            <!-- 功能简介 (对齐 cs-field) -->
            <div class="ca-field">
              <label>功能简介 <span class="req">*</span></label>
              <textarea
                v-model.trim="form.description"
                rows="2"
                placeholder="一句话说明这个智能体能解决什么问题"
                maxlength="120"
              />
              <span v-if="errors.description" class="ca-field__err">{{ errors.description }}</span>
              <span v-else class="ca-field__hint">{{ form.description.length }} / 120</span>
            </div>

            <!-- 所属分类 (对齐 cs-chips) -->
            <div class="ca-field">
              <label>所属分类</label>
              <div class="ca-chips">
                <button
                  v-for="c in CATEGORIES"
                  :key="c.key"
                  type="button"
                  class="ca-chip"
                  :class="{ 'is-active': form.category === c.key }"
                  @click="form.category = c.key"
                >
                  <span class="ca-chip__dot" :class="['is-' + c.key]" />
                  {{ c.name }}
                </button>
              </div>
            </div>

            <!-- 主题色 + 图标 (对齐 cs-row) -->
            <div class="ca-row">
              <div class="ca-field ca-field--half">
                <label>主题色</label>
                <div class="ca-colors">
                  <button
                    v-for="c in COLORS"
                    :key="c"
                    type="button"
                    class="ca-color-dot"
                    :class="{ 'is-active': form.color_theme === c }"
                    :style="{ background: c }"
                    @click="form.color_theme = c"
                  />
                </div>
              </div>
              <div class="ca-field ca-field--half">
                <label>图标</label>
                <div class="ca-icons">
                  <button
                    v-for="ic in ICONS"
                    :key="ic"
                    type="button"
                    class="ca-icon-btn"
                    :class="{ 'is-active': form.icon === ic }"
                    @click="form.icon = ic"
                  >
                    <el-icon :size="16"><component :is="iconComp(ic)" /></el-icon>
                  </button>
                </div>
              </div>
            </div>

            <!-- 高级设置 (对齐 cs-details) -->
            <details class="ca-details">
              <summary>高级设置(可选)</summary>
              <div class="ca-field">
                <label>触发命令</label>
                <div class="ca-trigger">
                  <span class="ca-trigger__prefix">/</span>
                  <input
                    v-model.trim="form.trigger_cmd"
                    type="text"
                    placeholder="mybot"
                    maxlength="40"
                  />
                </div>
                <span class="ca-field__hint">在聊天输入框中以 /xxx 形式快速调用</span>
              </div>
              <div class="ca-field">
                <label>人设 / 系统提示词</label>
                <textarea
                  v-model="form.system_prompt"
                  rows="5"
                  placeholder="你是一位专业的【角色】,擅长【领域】...&#10;回答要求:&#10;1. ...&#10;2. ..."
                  maxlength="2000"
                  class="ca-prompt"
                />
                <span class="ca-field__hint">{{ form.system_prompt.length }} / 2000 · 定义智能体的角色定位、回答风格、注意事项等</span>
              </div>
            </details>
          </form>

          <!-- ============== FOOTER (对齐 cs-modal__foot) ============== -->
          <footer class="ca-modal__foot">
            <button type="button" class="btn btn--ghost" @click="onClose">取消</button>
            <button type="button" class="btn btn--primary" :disabled="submitting" @click="handleSubmit">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6 9 17l-5-5"/></svg>
              {{ submitting ? '创建中...' : '创建智能体' }}
            </button>
          </footer>
        </div>
      </div>
    </Transition>
  </Teleport>
</template>

<script setup>
import { ref, reactive, markRaw, watch, computed } from 'vue'
import {
  Cellphone, Connection, Cpu, Link, MagicStick, Star, StarFilled, Discount,
  Setting, Monitor, Histogram, DataAnalysis, Headset, Document, Tools,
  Notebook, Compass, Lightning, Aim, ChatLineSquare, User, DataLine, PieChart,
} from '@element-plus/icons-vue'
import { useToastStore } from '@/stores/toast'

const props = defineProps({ open: { type: Boolean, default: false } })
const emit = defineEmits(['close', 'submit'])
const toast = useToastStore()

/* ============== 分类 (与 Skills 命名一致) ============== */
const CATEGORIES = [
  { key: 'custom',   name: '通用自定义' },
  { key: 'terminal', name: '终端' },
  { key: 'network',  name: '网络' },
  { key: 'payload',  name: '载荷' },
  { key: 'e2e',      name: '全链路' },
]

/* ============== 主题色 (对齐 cs-colors) ============== */
const COLORS = ['#5b8def', '#36cbcb', '#fbb337', '#f25c54', '#7ed321', '#b287e6', '#ff8e53', '#26bbaa']

/* ============== 图标库 (8 选) ============== */
const ICONS = [
  'smart_toy', 'auto_awesome', 'edit', 'description', 'language',
  'analytics', 'support_agent', 'psychology',
]

/* 后端 Material 图标名 -> Element Plus 图标组件 */
const ICON_MAP = {
  smartphone: Cellphone, language: Connection, memory: Cpu, checklist: Link,
  smart_toy: MagicStick, auto_awesome: Star, edit: Document, description: Document,
  code: Monitor, analytics: Histogram, support_agent: ChatLineSquare, psychology: User,
  monitor_heart: Headset, rocket_launch: Discount, workspace_premium: StarFilled,
  shield: Setting, insights: DataAnalysis, forum: ChatLineSquare,
}
function iconComp(name) { return markRaw(ICON_MAP[name] || MagicStick) }

const initialState = () => ({
  name: '',
  description: '',
  category: 'custom',
  color_theme: COLORS[0],
  icon: ICONS[0],
  trigger_cmd: '',
  system_prompt: '',
})

const form = reactive(initialState())
const errors = reactive({})
const submitting = ref(false)

function reset() {
  Object.assign(form, initialState())
  Object.keys(errors).forEach((k) => delete errors[k])
  submitting.value = false
}
watch(() => props.open, (v) => { if (v) reset() })

function onClose() {
  if (submitting.value) return
  emit('close')
}

function validate() {
  Object.keys(errors).forEach((k) => delete errors[k])
  if (!form.name) errors.name = '请输入智能体名称'
  else if (form.name.length > 30) errors.name = '名称不能超过 30 字'
  if (!form.description) errors.description = '请输入功能简介'
  else if (form.description.length > 120) errors.description = '简介不能超过 120 字'
  if (form.system_prompt.length > 2000) errors.system_prompt = '提示词不能超过 2000 字'
  return Object.keys(errors).length === 0
}

function handleSubmit() {
  if (!validate()) return
  submitting.value = true
  const draft = { ...form }
  emit('submit', draft)
  toast.success('智能体已创建', form.name)
  setTimeout(() => { submitting.value = false; emit('close') }, 200)
}

/* 兼容旧引用(避免在父组件调用时出现未使用警告) */
void computed
</script>

<style scoped>
/* ============== MASK (固定居中, 滚动不漂移) ============== */
.ca-mask {
  position: fixed; inset: 0; z-index: 1000;
  background: color-mix(in srgb, var(--ink-1, #0f172a) 55%, transparent);
  backdrop-filter: blur(6px);
  -webkit-backdrop-filter: blur(6px);
  display: flex;
  align-items: center;       /* 垂直居中 */
  justify-content: center;   /* 水平居中 */
  padding: 24px;
  overflow-y: auto;
}
.ca-modal {
  position: relative;
  width: 100%; max-width: 600px;
  max-height: calc(100vh - 48px);
  margin: auto;
  background: var(--surface-1, #fff);
  border-radius: 16px;
  box-shadow: 0 24px 64px rgba(15, 23, 42, 0.24);
  display: flex; flex-direction: column;
  overflow: hidden;
  align-self: center;
}

/* ============== HEADER (对齐 cs-modal__head) ============== */
.ca-modal__head {
  display: flex; align-items: flex-start; justify-content: space-between;
  padding: 20px 24px; border-bottom: 1px solid var(--border-1, #e5e7eb);
}
.ca-modal__title { display: flex; gap: 12px; align-items: center; min-width: 0; }
.ca-modal__icon {
  width: 40px; height: 40px; border-radius: 10px;
  display: flex; align-items: center; justify-content: center;
  flex-shrink: 0;
}
.ca-modal__title h3 { margin: 0; font-size: 16px; font-weight: 600; color: var(--ink-1, #0f172a); }
.ca-modal__title p  { margin: 2px 0 0; font-size: 12px; color: var(--ink-3, #6b7280); }
.ca-modal__close {
  width: 32px; height: 32px; border: none; background: transparent;
  display: flex; align-items: center; justify-content: center;
  border-radius: 8px; color: var(--ink-2, #475569); cursor: pointer;
  transition: all 0.15s;
  flex-shrink: 0;
}
.ca-modal__close:hover { background: var(--surface-2, #f1f5f9); color: var(--ink-1, #0f172a); }
.ca-modal__close svg { width: 18px; height: 18px; }

/* ============== BODY ============== */
.ca-modal__body {
  padding: 20px 24px; overflow-y: auto; flex: 1;
  display: flex; flex-direction: column; gap: 16px;
}
.ca-field { display: flex; flex-direction: column; gap: 6px; }
.ca-field label { font-size: 13px; font-weight: 500; color: var(--ink-2, #334155); }
.ca-field .req { color: #f5365c; margin-left: 2px; }

.ca-field input, .ca-field textarea {
  border: 1px solid var(--border-1, #d1d5db);
  background: var(--surface-1, #fff);
  color: var(--ink-1, #0f172a);
  border-radius: 8px; padding: 8px 12px; font-size: 13px;
  font-family: inherit; resize: vertical;
  transition: border-color 0.15s, box-shadow 0.15s;
  width: 100%;
}
.ca-field input:focus, .ca-field textarea:focus {
  outline: none;
  border-color: var(--accent, #5b8def);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent, #5b8def) 20%, transparent);
}
.ca-field__hint { font-size: 11px; color: var(--ink-3, #6b7280); }
.ca-field__err  { font-size: 11px; color: #f5365c; }

/* ============== CHIPS (对齐 cs-chips) ============== */
.ca-chips { display: flex; flex-wrap: wrap; gap: 6px; }
.ca-chip {
  display: inline-flex; align-items: center; gap: 6px;
  padding: 5px 12px; font-size: 12px; border-radius: 999px;
  border: 1px solid var(--border-1, #d1d5db);
  background: var(--surface-1, #fff);
  color: var(--ink-2, #475569); cursor: pointer;
  font-family: inherit;
  transition: all 0.15s;
}
.ca-chip:hover { border-color: var(--accent, #5b8def); color: var(--accent, #5b8def); }
.ca-chip.is-active {
  background: var(--accent, #5b8def); color: #fff; border-color: var(--accent, #5b8def);
}
.ca-chip__dot {
  width: 6px; height: 6px; border-radius: 50%;
  background: currentColor; opacity: 0.6;
}
.ca-chip.is-active .ca-chip__dot { background: #fff; opacity: 1; }
/* 分类小圆点着色 (与 agent-card__cat 保持一致) */
.ca-chip__dot.is-terminal { background: #10b981; }
.ca-chip__dot.is-network  { background: #3b82f6; }
.ca-chip__dot.is-payload  { background: #f59e0b; }
.ca-chip__dot.is-e2e      { background: var(--accent, #5b8def); }
.ca-chip__dot.is-custom   { background: var(--ink-3, #6b7280); }

/* ============== ROW (主题色 + 图标) ============== */
.ca-row { display: flex; gap: 16px; }
.ca-field--half { flex: 1; }

.ca-colors { display: flex; gap: 6px; flex-wrap: wrap; }
.ca-color-dot {
  width: 24px; height: 24px; border-radius: 50%;
  border: 2px solid transparent; cursor: pointer;
  transition: transform 0.15s;
}
.ca-color-dot:hover { transform: scale(1.1); }
.ca-color-dot.is-active {
  border-color: var(--ink-1, #0f1226);
  box-shadow: 0 0 0 2px var(--surface-1, #fff) inset;
}

.ca-icons { display: grid; grid-template-columns: repeat(8, 1fr); gap: 4px; }
.ca-icon-btn {
  aspect-ratio: 1; border: 1px solid var(--border-1, #d1d5db);
  background: var(--surface-1, #fff); border-radius: 6px;
  display: flex; align-items: center; justify-content: center;
  color: var(--ink-2, #475569); cursor: pointer;
  transition: all 0.15s;
}
.ca-icon-btn:hover { color: var(--accent, #5b8def); border-color: var(--accent, #5b8def); }
.ca-icon-btn.is-active {
  background: color-mix(in srgb, var(--accent, #5b8def) 15%, transparent);
  border-color: var(--accent, #5b8def); color: var(--accent, #5b8def);
}

/* ============== DETAILS (高级设置 - 对齐 cs-details) ============== */
.ca-details {
  border: 1px dashed var(--border-1, #d1d5db);
  border-radius: 8px; padding: 8px 12px;
}
.ca-details summary {
  cursor: pointer; font-size: 12px; color: var(--ink-3, #6b7280);
  list-style: none;
  user-select: none;
}
.ca-details summary::before { content: '▸ '; transition: transform 0.15s; display: inline-block; }
.ca-details[open] summary::before { content: '▾ '; }
.ca-details[open] > .ca-field { margin-top: 12px; }

/* ============== TRIGGER (触发命令) ============== */
.ca-trigger {
  display: flex; align-items: stretch;
  border: 1px solid var(--border-1, #d1d5db);
  background: var(--surface-1, #fff);
  border-radius: 8px;
  overflow: hidden;
  transition: border-color 0.15s, box-shadow 0.15s;
}
.ca-trigger:focus-within {
  border-color: var(--accent, #5b8def);
  box-shadow: 0 0 0 3px color-mix(in srgb, var(--accent, #5b8def) 20%, transparent);
}
.ca-trigger__prefix {
  display: flex; align-items: center; justify-content: center;
  width: 36px; flex-shrink: 0;
  font-size: 14px; font-weight: 500;
  color: var(--ink-3, #6b7280);
  background: var(--surface-2, #f8fafc);
  border-right: 1px solid var(--border-1, #e5e7eb);
}
.ca-trigger input {
  flex: 1; border: 0; outline: 0;
  padding: 8px 12px;
  background: transparent;
  font-size: 13px;
  color: var(--ink-1, #0f172a);
  font-family: 'JetBrains Mono', Menlo, Consolas, monospace;
}

.ca-prompt {
  font-family: 'JetBrains Mono', Menlo, Consolas, monospace;
  font-size: 12.5px; line-height: 1.7;
}

/* ============== FOOTER (对齐 cs-modal__foot) ============== */
.ca-modal__foot {
  display: flex; justify-content: flex-end; gap: 8px;
  padding: 14px 24px;
  border-top: 1px solid var(--border-1, #e5e7eb);
  background: var(--surface-2, #f8fafc);
}

/* ============== BUTTONS (对齐 .btn) ============== */
.btn {
  display: inline-flex; align-items: center; gap: 6px;
  padding: 8px 18px; border-radius: 10px; font-size: 13px;
  border: 1px solid var(--line); background: var(--surface);
  color: var(--ink-2); cursor: pointer;
  font-family: inherit; font-weight: 500;
  transition: all 0.15s;
}
.btn:disabled { opacity: 0.6; cursor: not-allowed; }
.btn--ghost:hover { background: var(--surface-2, #f1f5f9); color: var(--ink-1); }
.btn--primary {
  background: var(--accent, #5b8def); color: #fff;
  border-color: var(--accent, #5b8def);
}
.btn--primary:hover:not(:disabled) { filter: brightness(1.08); }
.btn svg { width: 14px; height: 14px; }

/* ============== ANIMATIONS ============== */
.ca-fade-enter-active, .ca-fade-leave-active { transition: opacity 0.2s; }
.ca-fade-enter-active .ca-modal, .ca-fade-leave-active .ca-modal { transition: transform 0.2s; }
.ca-fade-enter-from, .ca-fade-leave-to { opacity: 0; }
.ca-fade-enter-from .ca-modal, .ca-fade-leave-to .ca-modal { transform: scale(0.96) translateY(8px); }

/* ============== RESPONSIVE (对齐 cs-modal) ============== */
@media (max-width: 640px) {
  .ca-mask { padding: 12px; }
  .ca-modal { max-height: calc(100vh - 24px); border-radius: 12px; }
  .ca-row { flex-direction: column; gap: 14px; }
  .ca-icons { grid-template-columns: repeat(6, 1fr); }
  .ca-modal__head, .ca-modal__body, .ca-modal__foot { padding-left: 18px; padding-right: 18px; }
}
</style>
